# -*- coding: utf-8 -*-
"""Assignment-008/9 (Letters Count).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DeGPNJtwtubgrcsOlF4x-Wbgg-K2kEGn
"""

my_dict = {}

soru = input("Please enter the sentence :")
for i  in soru :
  my_dict[i] = soru.count(i)
print(my_dict)